version: "3.9"

services:
  rocket_manager:
    build: ../ur-rocket-manager/

  user_manager:
    build: ../ur-user-manager/

  junk_manager:
    build: ../ur-junk-manager/

  frontend:
    build: ../ur-frontend/
