version: "3.9"

services:
  user_manager:
    image: nicholasdmartin/micro-rocket-user_manager:main
    container_name: user_manager
    ports:
      - 8001:80
    depends_on:
      - user_man_db
      - rabbitmq
    environment:
      - ROOT_PATH=/user-manager
      - MAX_WORKERS=1
      - REDIS_SERVICE=user_man_db
      - SERVICE_NAME=User Manager
      - STARTUP_TIME=2
      - SECRET_KEY=e9629f658c37859ab9d74680a3480b99265c7d4c89224280cb44a255c320661f

  rocket_manager:
    image: nicholasdmartin/micro-rocket-rocket_manager:main
    container_name: rocket_manager
    ports:
      - 8002:80
    depends_on:
      - rocket_man_db
      - rabbitmq
    environment:
      - ROOT_PATH=/rocket-manager
      - MAX_WORKERS=1
      - REDIS_SERVICE=rocket_man_db
      - SERVICE_NAME=Rocket Manager
      - USER_URL=http://localhost:8001/token
      - MIN_ENGINES=1
      - MAX_ENGINES=8
      - MIN_HEIGHT=20
      - MAX_HEIGHT=200
      - STARTUP_TIME=20
      - RF_DENSITY=750
      - WALL_THICKNESS=0.1
      - TIME_DELTA=1.0
      - MASS_FLOW=500

  junk_manager:
    image: nicholasdmartin/micro-rocket-junk_manager:main
    container_name: junk_manager
    depends_on:
      - rabbitmq
    environment:
      - STARTUP_TIME=20
      - JUNK_PROBABILITY=5
      - JUNK_ALT_MIN=10000
      - JUNK_ALT_MAX=1200000

  frontend:
    image: nicholasdmartin/micro-rocket-frontend:main
    container_name: frontend
    ports:
      - 5000:5000
    depends_on:
      - rocket_manager
      - user_manager

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    hostname: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672

  # Storage
  user_man_db:
    container_name: "user_man_db"
    image: "redis:alpine"

  rocket_man_db:
    container_name: "rocket_man_db"
    image: "redis:alpine"

  # Telemetry
  jaeger:
    container_name: "jaeger"
    image: jaegertracing/all-in-one:1.27
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411

  # Proxy
  nginx:
    image: opentracing/nginx-opentracing
    container_name: nginx
    depends_on:
      - frontend
      - user_manager
      - rocket_manager
      - jaeger
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./jaeger-config-nginx.json:/etc/jaeger-config.json
    ports:
      - 80:80
